[package]
name = "game"
version = "0.0.1"
edition.workspace = true

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
common = { path = "../common" }
winit.workspace = true
winit_input_helper.workspace = true
cgmath.workspace = true
