[workspace]
members = ["common", "game", "editor"]
resolver = "2"

[workspace.package]
edition = "2021"

[workspace.dependencies]
log = "0.4"
pixels = "0.9"
winit = "0.27.3"
winit_input_helper = "0.13"
cgmath = "0.18.0"

[profile.dev]
opt-level = 1

[profile.dev.package."*"]
opt-level = 3
