[workspace]
members = ["common", "game", "editor"]
resolver = "2"

[workspace.package]
edition = "2021"

[workspace.dependencies]
pixels = "*"
winit = "*"
winit_input_helper = "*"
cgmath = "0.18.0"

[profile.dev]
opt-level = 1

[profile.dev.package."*"]
opt-level = 3
